# Generated by Django 2.2.5 on 2019-09-11 21:41

import datetime
from django.db import migrations, models
import servicemanager.utils


class Migration(migrations.Migration):

    dependencies = [
        ('servicemanager', '0003_auto_20190911_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='birth_date',
            field=models.DateField(default=datetime.date(2001, 9, 11), validators=[servicemanager.utils.validate_legal_age]),
        ),
    ]
