# Generated by Django 2.2.5 on 2019-09-16 11:14

from django.db import migrations, models
import servicemanager.utils


class Migration(migrations.Migration):

    dependencies = [
        ('servicemanager', '0006_auto_20190916_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='birth_date',
            field=models.DateField(default=servicemanager.utils.get_default_birth_date, validators=[servicemanager.utils.validate_legal_age]),
        ),
    ]
