# Generated by Django 2.2.5 on 2019-09-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicemanager', '0007_auto_20190916_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('in progress', 'In progress'), ('cancelled', 'Cancelled')], default='In progress', max_length=11),
        ),
    ]
