# Generated by Django 2.2.5 on 2019-09-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicemanager', '0009_auto_20190916_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('In progress', 'In progress'), ('Cancelled', 'Cancelled')], default='in progress', max_length=11),
        ),
    ]
