# Generated by Django 2.2.5 on 2019-09-18 16:18

from django.db import migrations, models
import servicemanager.utils


class Migration(migrations.Migration):

    dependencies = [
        ('servicemanager', '0010_auto_20190916_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[servicemanager.utils.validate_amount]),
        ),
    ]
