# Generated by Django 2.2.5 on 2019-09-18 18:33

from django.db import migrations, models
import servicemanager.utils


class Migration(migrations.Migration):

    dependencies = [
        ('servicemanager', '0011_auto_20190918_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=100, validators=[servicemanager.utils.validate_name]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=100, validators=[servicemanager.utils.validate_name]),
        ),
    ]
